# permissions for end users to view catalogcaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalogcache-viewer-role
rules:
- apiGroups:
  - core.rukpak.io
  resources:
  - catalogcaches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.rukpak.io
  resources:
  - catalogcaches/status
  verbs:
  - get
